simulation:
    CHEBYSHEV_DISTANCE: 5
    GRID_SIZE: 15
    LLM_MAX_TOKENS: 2048
    LLM_MODEL: llama-3.3-70b-versatile
    LLM_TEMPERATURE: 0.7
    LOG_LEVEL: INFO
    MAX_CONCURRENT_REQUESTS: 5
    MAX_STEPS: 10
    NUM_ENTITIES: 3
    REQUEST_DELAY: 2.3
